### ISSUE TITLE
Error on "composer require rakoitde/shieldldap"

### ISSUE THREAD

**Issue by prashantarbat** [rakoitde/ci4-shield-ldap#2]
Receiving error message while "composer require rakoitde/shieldldap"

In PackageDiscoveryTrait.php line 376:
                                                                                                                  
  Could not find a matching version of package rakoitde/shieldldap. Check the package spelling, your version con  
  straint and that the package is available in a stability which matches your minimum-stability (stable).      

![Untitled](https://github.com/rakoitde/ci4-shield-ldap/assets/63440604/ea8cb333-9ebf-424f-90e2-f7fbc4cfe503)

**Comment by rakoitde** [comment]
Thank you for reporting the issue. I have corrected the installation instructions and tested them successfully in my environment. please check it out.
