### ISSUE TITLE
Can we use either either ldap username or email simultaneously

### ISSUE THREAD

**Issue by prashantarbat** [rakoitde/ci4-shield-ldap#4]
Hi,

I am creating CodeIgniter 4 project, where internal staff members are logged in with their domain credentials, but third-party vendors or external users can be logged in with their email. 

In my current project I am using Shield for Authentication & Authorization, modified the login use email instead of username, & working fine.

As subject speaks, can we use either ldap username or email simultaneously?

Regards,
Prashant

**Comment by rakoitde** [comment]
Please excuse the late reply. But no, unfortunately that is not possible.
